/oak1:
  ros__parameters:
    camera:
      i_ip: 10.95.76.12
      i_nn_type: none
    imu:
      i_enable_rotation: true
      i_message_type: IMU_WITH_MAG_SPLIT
      i_rotation_vector_type: ROTATION_VECTOR
      i_rot_cov: 0.0001
      i_gyro_mode: GYROSCOPE_CALIBRATED
      i_mag_mode: MAGNETOMETER_CALIBRATED
    stereo:
      i_align_depth: true
      i_board_socket_id: 2
      i_subpixel: true
      i_right_rect_publish_topic: true
      i_right_rect_synced: false
