/oak0:
  ros__parameters:
    camera:
      i_ip: 10.95.76.10
      i_mx_id: 18443010D1D8920F00
      i_nn_type: none
    stereo:
      i_align_depth: true
      i_board_socket_id: 2
      i_subpixel: true
      i_right_rect_publish_topic: true
      i_right_rect_synced: false

/oak1:
  ros__parameters:
    camera:
      i_ip: 10.95.76.11
      i_mx_id: 18443010F1E8920F00
      i_nn_type: none
    stereo:
      i_synced: false
      i_align_depth: true
      i_board_socket_id: 2
      i_subpixel: false
