/oak0:
  ros__parameters:
    camera:
      i_ip: 10.95.76.10
      i_mx_id: 18443010D1D8920F00
      i_pipeline_type: RGBD
      i_nn_type: none
      i_laser_dot_brightness: 1000
    rgb:
      i_publish_topic: true
      i_fps: 30.0
      i_isp_num: 1
      i_isp_den: 3
      i_output_isp: true
    left:
      i_publish_topic: false
      i_fps: 30.0
    right:
      i_publish_topic: false
      i_fps: 30.0
    stereo:
      i_align_depth: true
      i_subpixel: true
      i_stereo_conf_threshold: 110
      i_enable_brightness_filter: false
      i_brightness_filter_min_brightness: 1
      i_brightness_filter_max_brightness: 225
      i_enable_decimation_filter: true
      i_publish_left_rect: false
      i_publish_right_rect: false

/oak1:
  ros__parameters:
    camera:
      i_ip: 10.95.76.11
      i_mx_id: 18443010F1E8920F00
      i_pipeline_type: RGBD
      i_nn_type: none
      i_laser_dot_brightness: 1000
    rgb:
      i_publish_topic: true
      i_fps: 30.0
      i_isp_num: 1
      i_isp_den: 3
      i_output_isp: true
    left:
      i_publish_topic: false
      i_fps: 10.0
    right:
      i_publish_topic: false
      i_fps: 10.0
    stereo:
      i_align_depth: true
      i_subpixel: true
      i_stereo_conf_threshold: 110
      i_enable_brightness_filter: false
      i_brightness_filter_min_brightness: 1
      i_brightness_filter_max_brightness: 225
      i_enable_decimation_filter: true
      i_publish_left_rect: false
      i_publish_right_rect: false
